version: "3.9"

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - 3000:3000
    environment:
      APP_SESSION_SECRET: "${APP_SESSION_SECRET}"
      APP_NAME: "${APP_NAME}"

  terraform:
    image: hashicorp/terraform:1.2.7
    profiles:
      - utilities
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform
    environment:
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      HEROKU_EMAIL: "${HEROKU_EMAIL}"
      HEROKU_API_KEY: "${HEROKU_API_KEY}"
      TF_VAR_heroku_basename: "${TF_VAR_heroku_basename}"

  tfsec:
    image: aquasec/tfsec:v1.27.1
    profiles:
      - utilities
    working_dir: /terraform
    command: .
    volumes:
      - ./terraform:/terraform
