name: Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      apply_changes: true
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      TF_VAR_heroku_basename: ${{ secrets.TF_VAR_heroku_basename }}
