name: Push

on:
  push:

env:
  APP_NAME: CI Test
  APP_SESSION_SECRET: insecure-secret

jobs:
  test:
    name: yarn
    uses: ./.github/workflows/yarn.yml
    with:
      script: coverage

  lint:
    name: yarn
    uses: ./.github/workflows/yarn.yml
    with:
      script: lint

  tfsec:
    uses: ./.github/workflows/tfsec.yml

  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      apply_changes: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      TF_VAR_heroku_basename: ${{ secrets.TF_VAR_heroku_basename }}
