name: terraform

on:
  workflow_call:
    inputs:
      apply_changes:
        required: false
        default: false
        type: boolean
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      HEROKU_EMAIL:
        required: true
      HEROKU_API_KEY:
        required: true
      TF_VAR_heroku_basename:
        required: true

jobs:
  run:
    name: ${{ inputs.apply_changes && 'apply' || 'plan' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache installed terraform providers
        uses: actions/cache@v3
        with:
          path: terraform/.terraform
          key: v1-${{ hashFiles('terraform/.terraform.lock.hcl') }}

      - name: Initialize terraform
        run: docker compose run terraform init
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          TF_VAR_heroku_basename: ${{ secrets.TF_VAR_heroku_basename }}

      - name: Plan infrastructure changes
        run: docker compose run terraform plan -out planned
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          TF_VAR_heroku_basename: ${{ secrets.TF_VAR_heroku_basename }}

      - name: Apply infrastructure changes
        if: inputs.apply_changes
        run: docker compose run terraform apply planned
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          TF_VAR_heroku_basename: ${{ secrets.TF_VAR_heroku_basename }}
