name: yarn

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

jobs:
  jest:
    name: run ${{ inputs.script }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ${{ inputs.script }}
        run: docker compose run app ${{ inputs.script }}
